name: Sourcetrail CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build software using docker
    strategy:
        matrix:
          image: [Dockerfile.P9, Dockerfile.sisyphus]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: docker build . --file ${{ matrix.image }} --tag build-environment
      - run: docker run --privileged=true -i --log-driver=none -a stdin -a stdout -a stderr -v "$(pwd)":/app build-environment


